# Generated by Django 4.2.3 on 2023-07-24 08:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='deperment',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='joinin_date',
            field=models.DateField(verbose_name=datetime.date.today),
        ),
    ]
