# Generated by Django 4.2.3 on 2023-07-26 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='user_type',
            field=models.CharField(blank=True, default='General', max_length=100),
        ),
    ]
