# Generated by Django 4.2.3 on 2023-07-24 08:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_student_deperment_alter_student_joinin_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='joinin_date',
            field=models.DateField(blank=True, verbose_name=datetime.date.today),
        ),
    ]
