# Generated by Django 4.2.3 on 2023-07-24 08:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_student_joinin_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='joinin_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_address',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_email',
            field=models.EmailField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_name',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_phone',
            field=models.CharField(default='None', max_length=10),
        ),
    ]
