# Generated by Django 4.2.3 on 2023-07-26 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_student_org_alter_teacher_org'),
    ]

    operations = [
        migrations.RenameField(
            model_name='org',
            old_name='user_type',
            new_name='customer_type',
        ),
    ]
