# Generated by Django 4.2.3 on 2023-07-26 17:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_rename_user_type_org_customer_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FACULTY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=100)),
                ('faculty_email', models.EmailField(max_length=100)),
                ('faculty_phone', models.CharField(max_length=10)),
                ('faculty_address', models.CharField(max_length=100)),
                ('faculty_photo', models.ImageField(blank=True, upload_to='faculty_photo/')),
                ('deperment', models.CharField(default='None', max_length=100)),
                ('joinin_date', models.DateField(default=datetime.date.today)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.org')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='TEACHER',
        ),
    ]
