# Generated by Django 4.2.3 on 2023-07-26 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_faculty_delete_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='deperment',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='deperment',
            new_name='department',
        ),
    ]
