# Generated by Django 4.2.3 on 2023-07-26 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_deperment_faculty_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='session',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='session',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='department',
            field=models.CharField(max_length=100),
        ),
    ]
