# Generated by Django 4.2.3 on 2023-07-26 13:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrolledStudents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('session', models.CharField(max_length=100)),
                ('student_info_file', models.FileField(upload_to='student_info_files/')),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('announcement_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('time', models.TimeField(default=datetime.time(13, 13, 11, 139114))),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.org')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
