# Generated by Django 4.2.3 on 2023-08-19 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgAdmin', '0003_alter_announcement_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('session', models.CharField(max_length=100)),
                ('semester_start_date', models.DateField(default=datetime.date.today)),
                ('semester_end_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.AlterField(
            model_name='announcement',
            name='time',
            field=models.TimeField(default=datetime.time(17, 17, 0, 855681)),
        ),
    ]
