# Generated by Django 4.2.3 on 2023-07-24 06:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgAdmin', '0005_alter_announcement_announcement_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='time',
            field=models.TimeField(default=datetime.time(6, 21, 8, 887830)),
        ),
    ]
