# Generated by Django 4.2.3 on 2023-07-26 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgAdmin', '0005_alter_announcement_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitedFaculty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('session', models.CharField(max_length=100)),
                ('faculty_info_file', models.FileField(upload_to='faculty_info_files/')),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.AlterField(
            model_name='announcement',
            name='time',
            field=models.TimeField(default=datetime.time(17, 39, 27, 306288)),
        ),
    ]
