# Generated by Django 4.2.3 on 2023-07-26 17:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgAdmin', '0006_recruitedfaculty_alter_announcement_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='time',
            field=models.TimeField(default=datetime.time(17, 54, 6, 333122)),
        ),
    ]
