# Generated by Django 4.2.3 on 2023-07-24 07:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgAdmin', '0007_alter_announcement_posted_by_alter_announcement_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrolledStudents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('session', models.CharField(max_length=100)),
                ('student_info_file', models.FileField(upload_to='student_info_files')),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.AlterField(
            model_name='announcement',
            name='time',
            field=models.TimeField(default=datetime.time(7, 53, 18, 337297)),
        ),
    ]
