# Generated by Django 4.2.3 on 2023-07-24 08:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgAdmin', '0008_enrolledstudents_alter_announcement_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='time',
            field=models.TimeField(default=datetime.time(8, 32, 25, 941451)),
        ),
        migrations.AlterField(
            model_name='enrolledstudents',
            name='student_info_file',
            field=models.FileField(upload_to='student_info_files/'),
        ),
    ]
