# Generated by Django 4.2.3 on 2023-07-28 11:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgAdmin', '0009_alter_announcement_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisingDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('session', models.CharField(max_length=100)),
                ('advising_file', models.FileField(upload_to='advising_files/')),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='PreAdvisingDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('session', models.CharField(max_length=100)),
                ('pre_advising_file', models.FileField(upload_to='pre_advising_files/')),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.AlterField(
            model_name='announcement',
            name='time',
            field=models.TimeField(default=datetime.time(11, 26, 47, 502082)),
        ),
    ]
