# Generated by Django 4.2.3 on 2023-07-24 08:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgAdmin', '0009_alter_announcement_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='time',
            field=models.TimeField(default=datetime.time(8, 44, 7, 219022)),
        ),
    ]
