# Generated by Django 4.2.3 on 2023-07-29 07:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgAdmin', '0010_advisingdetails_preadvisingdetails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='time',
            field=models.TimeField(default=datetime.time(7, 16, 28, 707132)),
        ),
    ]
