# Generated by Django 4.2.3 on 2023-07-24 08:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgAdmin', '0011_alter_announcement_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='time',
            field=models.TimeField(default=datetime.time(8, 51, 30, 605467)),
        ),
    ]
