# Generated by Django 4.2.3 on 2023-07-29 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advising', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advising',
            old_name='adving_ending_day',
            new_name='advising_ending_day',
        ),
        migrations.RenameField(
            model_name='advising',
            old_name='adving_ending_time',
            new_name='advising_ending_time',
        ),
        migrations.RenameField(
            model_name='advising',
            old_name='adving_staring_day',
            new_name='advising_staring_day',
        ),
        migrations.RenameField(
            model_name='advising',
            old_name='adving_staring_time',
            new_name='advising_staring_time',
        ),
        migrations.RenameField(
            model_name='preadvising',
            old_name='adving_day',
            new_name='advising_day',
        ),
        migrations.RenameField(
            model_name='preadvising',
            old_name='adving_end_time',
            new_name='advising_end_time',
        ),
        migrations.RenameField(
            model_name='preadvising',
            old_name='adving_start_time',
            new_name='advising_start_time',
        ),
    ]
